module.exports = {
    important: true,
    purge: false,
    theme: {
        screens: {
            sm: '568px',
            md: '768px',
            lg: '1024px',
            xl: '1444px',
        },
        fontFamily: {
            body: ['Montserrat', 'Helvetica', 'sans-serif'],
            button: ['Montserrat', 'Helvetica', 'sans-serif'],
        },
        inset: {
            '0': '0',
            auto: 'auto',
            '0.2': '0.2rem',
            '0.25': '0.25rem',
            '0.3': '0.3rem',
            '0.4': '0.4rem',
            '0.5': '0.5rem',
            '0.6': '0.6rem',
            '0.7': '0.7rem',
            '0.75': '0.75rem',
            '0.8': '0.8rem',
            '0.9': '0.9rem',
            '1': '1rem',
            '1.1': '1.1rem',
            '1.2': '1.2rem',
            '1.25': '1.25rem',
            '1.3': '1.3rem',
            '1.4': '1.4rem',
            '1.5': '1.5rem',
            '1.6': '1.6rem',
            '1.7': '1.7rem',
            '1/2': '50%',
        },
        extend: {},
        minHeight: {
            '0': '0',
            '1/4': '25%',
            '1/2': '50%',
            '3/4': '75%',
        },
    },
    variants: {},
    plugins: [],
};
